name: ChestShop
main: ChestShop\ChestShop
version: 3.0.0
api: [4.0.0]
load: POSTWORLD
author: MinecrafterJPN
description: A PocketMine-MP plugin which enables you to open a chest shop using a sign
website: https://github.com/poggit-orphanage/ChestShop
depend:
 - EconomyAPI
extensions:
- sqlite3
commands:
  id:
    description: Search item ID
    usage: "/id <itemname>"
    permission: chestshop.command.id
permissions:
  chestshop:
    default: op
    description: "Allows using all the ChestShop things"
    children:
      chestshop.command:
        default: op
        description: "Allows using all the PocketMoney commands"
        children:
          chestshop.command.id:
            default: true
            description: "Allows searching item ID"
      chestshop.makeshop:
        default: op
        description: "Allows making chest shops"
        children:
          chestshop.makeshop.1:
            default: true
            description: "Allows making 1 chest shop"
          chestshop.makeshop.unlimited:
            default: op
            description: "Allows making unlimited chest shops"
      chestshop.admin:
        default: op
        description: "Allows administration of any chest shops"